### ISSUE TITLE
cannot take in len([])

### ISSUE THREAD

**Issue by kpyuan** [sashagutfraind/musketeer#3]
Checking original graph ... Traceback (most recent call last):
  File "musketeer.py", line 272, in <module>
    new_G = algorithms.generate_graph(G, params=params)
  File "musketeer-master/musketeer-master/algorithms.py", line 811, in generate_graph
    graphutils.graph_sanity_test(G, params)
  File "musketeer-master/musketeer-master/graphutils.py", line 672, in graph_sanity_test
    print 'Warning: self-loops detected (%d)'%len(selfloops)
TypeError: object of type 'generator' has no len()

**Comment by sashagutfraind** [comment]
Thanks for reporting this.  Which version of Python and NetworkX are you using?

**Comment by kpyuan** [comment]
Hi Sasha,
Thank you for replying. I'm using python 2.7.12 and NetworkX 2.1

**Comment by sashagutfraind** [comment]
This problem is due a change in NX.  I am committing a fix.

**Comment by HankyuJang** [comment]
```
(py27) C:\Users\Hankyu\musketeer>python musketeer.py -f data-samples/arenas_email.edges -t edgelist -p "{'node_growth_rate':[0.005, 0.001], 'edge_edit_rate':[0.05, 0.04, 0.03], 'node_edit_rate':[0.07, 0.06, 0.05]}" -o output/test.dot
random number generator seed: 402088
Loading: data-samples/arenas_email.edges
Default weight is 1. To indicate weight, each line should use the format: node1 node2 {'weight':positive_wt}
Generating ...
Checking original graph ... Traceback (most recent call last):
  File "musketeer.py", line 272, in <module>
    new_G = algorithms.generate_graph(G, params=params)
  File "C:\Users\Hankyu\musketeer\algorithms.py", line 811, in generate_graph
    graphutils.graph_sanity_test(G, params)
  File "C:\Users\Hankyu\musketeer\graphutils.py", line 672, in graph_sanity_test
    print 'Warning: self-loops detected (%d)'%len(selfloops)
TypeError: object of type 'generator' has no len()
```
I am getting the same error. Is the error fixed?

I am using python 2.7.15 and NetworkX 2.1

**Comment by HankyuJang** [comment]
I downgraded the `networkx` version to 1.11 and now it's working fine.

**Comment by sashagutfraind** [comment]
NX had significant changes in the APIs in recent versions - I regret the trouble it has been causing.
